"""Added title column to Quiz table

Revision ID: 3b6ecd3741aa
Revises: 8dc3e3986ec7
Create Date: 2025-03-19 14:51:05.408419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b6ecd3741aa'
down_revision = '8dc3e3986ec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint("uq_quiz_title", ['title'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
