"""Added Completion minutes and completion seconds in Score table

Revision ID: 789b8bce3d08
Revises: 3b6ecd3741aa
Create Date: 2025-03-20 08:01:59.900530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '789b8bce3d08'
down_revision = '3b6ecd3741aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completion_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completion_seconds', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_column('completion_seconds')
        batch_op.drop_column('completion_minutes')

    # ### end Alembic commands ###
